apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Set up Kustomize.
- name: Set up Kustomize
  run: |-
    curl -sfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz | tar -xzf -
    sudo mv kustomize /usr/local/bin/
resources:
  - ./deployment.yml
  - ./service.yml

commonLabels:
  app: foobar
